apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 443
      targetPort: 443
  selector: {}
---
kind: Endpoints
apiVersion: v1
metadata:
  name: my-service
subsets:
  - addresses:
      - ip: 172.0.0.1
    ports:
      - port: 443
        name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: https
  name: my-ingress
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: my-service
              servicePort: 443
            path: /
