apiVersion: v1
kind: Service
metadata:
  name: httpbin
spec:
  type: ExternalName
  externalName: httpbin.org
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: https
    nginx.ingress.kubernetes.io/upstream-vhost: httpbin.org
  name: httpbin
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: httpbin
              servicePort: 443
            path: /
