apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-greeter-server
spec:
  selector:
    matchLabels:
      run: grpc-greeter-server
  replicas: 2
  template:
    metadata:
      labels:
        run: grpc-greeter-server
    spec:
      containers:
      - name: main
        image: nstogner/grpc-greeter-server:v1
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-greeter-server
  labels:
    run: grpc-greeter-server
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 50051
  selector:
    run: grpc-greeter-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grpc-greeter-server
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: "greeter.sandbox"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grpc-greeter-server
            port:
              number: 80
  tls:
    - secretName: my-tls-secret
      hosts:
      - greeter.sandbox
